---
title: "BCB430 Report"
author: "Jiaqi Ma"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide  
    theme: journal
    fig.caption: true
    toc: true                  
    toc_depth: 3                
    toc_float: true
bibliography: BCB430.bib
link-citations: true
nocite: '@*'
---

```{=html}
<style>
body {
  font-size: 16px;
}

caption {
  font-size: 14px;
  font-style: italic;
}
</style>
```

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
                      warning = FALSE, # suppressing warning messages
                      message = FALSE,
                      knitr.kable.max_rows = 5)
```

# Introduction

...

# Objective

...

# Method

...

## Animal Model

To be done in report

## Data Source

-    Single cell RNA-seq (scRNA-seq)
-    Origional paper: [Jin et al, 2025](https://doi.org/10.1038/s41586-024-08350-8)
-    Deposited in [Neuroscience Multi-omic Data Archive (NeMO)](https://assets.nemoarchive.org/dat-61kfys3)
-    Download url: https://data.nemoarchive.org/other/grant/Mouse_Aging/zeng/transcriptome/scell/10x_v3/mouse/processed/counts/Mouse_Aging_10Xv3_normalized_20241115.h5ad.tar
-    Note: Only Hippocampal formation (HPF) data were subjected to this analysis

[Jin et al (2025)](https://doi.org/10.1038/s41586-024-08350-8) sequenced brain sample collected from 44 aged mice (20 female, 24 male) and 64 young adult mice (31 female, 33 male) using Illumina NovaSeq6000 sequencing system ([Modi et al, 2021](https://doi-org.myaccess.library.utoronto.ca/10.1007/978-1-0716-1099-2_2)) and 10X Genomics CellRanger pipline (v.6.0.0) to assemble sequenced reads to `mm10/gencode.vM23` reference genome ([Frankish et al, 2019](https://doi-org.myaccess.library.utoronto.ca/10.1093/nar/gky955)). The raw sequence data contain `2,777,165` cells categorized in 6 major regions, 16 broad regions.

The 6 major regions were:

1. Isocortex
2. Hippocampal formation (HPF)
3. Hypothalamus (HY)
4. Cerebral nulei (CNU)
5. Midbrain
6. Hindbrain

## Packages Usage

[Jin et al (2025)](https://doi.org/10.1038/s41586-024-08350-8) conduced clustering using unpublished, in-house developed R package `scrattch.bigcat (v.0.0.1)` (https://github.com/AllenInstitute/scrattch.bigcat), which is a sub-package of `scrattch` package (https://alleninstitute.github.io/scrattch/) optimized for extremely large single cell dataset by support parallel computing and in-disk data access. However, because [scrattch.bigcat (v.0.0.1)](https://github.com/AllenInstitute/scrattch.bigcat) wasn't formally released, it was poorly documented and failed to function on local lab machine after weeks' attempt to rescue. Thus, an alternative sub-package of [scrattch](https://alleninstitute.github.io/scrattch/), `scrattch.hicat` (https://github.com/AllenInstitute/scrattch.hicat), was utilized. [scrattch.hicat](https://github.com/AllenInstitute/scrattch.hicat) doesn't support parallel computing and in-disk data access, but provide better documentation.

[Seurat](https://satijalab.org/seurat/) ([Hao et al, 2023](https://satijalab.org/seurat/)) was utilized as basic frame work, to take advantage of it mature pipeline.

## Data loading and sub-setting

The downloaded data is in `.h5ad`, popular single-cell transctiptome format in python ecosystem. [annadataR](https://doi.org/10.1101/2025.08.18.669052) was utilized to read `.h5ad` file into R and converted to `seurat object`, basic functional unit in [Seurat](https://satijalab.org/seurat/) pipeline. Then subset the whole HPF dataset by neuro/glia, age, sex, sub-region (roi) to the following subsets for the sake of data management.

1. `SeuratObj` (Whole HPF)
2. `subset_obj` (Random 3k subset of `SeuratObj`)
3. `neuro_seuratobj` (Neuron)
4. `Non_neuro_seuratobj` (Glia)
5. `zero_doublet_seuratobj` (Cells with zero doublet score)
6. `male_seuratobj` (male)
7. `female_seuratobj` (female)
8. `adult_seuratobj` (adult)
9. `aged_seuratobj` (aged)
10. `ENT_seuratobj` (Entorhinal cortex)
11. `HIP_seuratobj` (Hippocampus)
12. `HIP_CA_seuratobj` (Hippocampus, Cornu Ammonis)
13. `PAR_POST_PRE_SUB_ProS_seuratobj` (Hippocampal-subicular)

## Exploritory Data Analysis

[ggplot2](https://ggplot2.tidyverse.org/) was utilized for visualization. Cell sub_class, roi, sex, age, and Doublet_score, one of the quality control score utilized by [Jin et al (2025)](https://doi.org/10.1038/s41586-024-08350-8), proposed by [McGinnis (2019)](https://doi.org/10.1016/j.cels.2019.03.003), were plotted and examined.


## Normalization and quality control

The normalization and quality control step were conduced by [Jin et al (2025)](https://doi.org/10.1038/s41586-024-08350-8). The raw counts were log-transformed and z-score normalized. Cells which number of gene detected < 1000 OR QC score < 50 OR Doublet score > 0.3 were removed.

## Clustering

Mention the poor-documented `bigcat` pacakge, note alternation usage of `hicat` pacakge

## Differential Gene Expression Analysis

Use `Seurat` to find DEGs along three aspect, sex, roi, and age. Include script to plot and normalize number of DEGs and modified ranking

## Synteny exploration

Manually browse top DEGs on UCSC genome browser (mm10)

## Reciprical BLAST

Reciprocally BLAST X and Y GM47283 homologous, and against human genome

## Read Assembly algorithm assessment

Cite 10x genomics, cell ranger, STAR

# Result

...

# Discussion

...

# References {#references}
